name: Performance Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start application
        run: |
          npm start &
          # Wait for the server to start
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: "./.lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Comment PR with Lighthouse results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Lighthouse 결과를 읽어서 PR에 코멘트로 추가
            const results = fs.readFileSync('./lighthouse-results.json', 'utf8');
            const data = JSON.parse(results);

            const comment = `## 🚀 Lighthouse Performance Results

            **Performance Score:** ${data.lhr.categories.performance.score * 100}
            **Accessibility Score:** ${data.lhr.categories.accessibility.score * 100}
            **Best Practices Score:** ${data.lhr.categories['best-practices'].score * 100}
            **SEO Score:** ${data.lhr.categories.seo.score * 100}

            [View full report](${data.lhr.finalUrl})`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
